export const SLOWLY_PHASES = ['situation','feelings','needs','distill','expression','action','optionalRest','record','ended'] as const;
export type SlowlyPhase = typeof SLOWLY_PHASES[number];
export type CompanionKind = 'need'|'strategy'|'insight';
export type SlowlyOutcome = 'completed'|'ended-early';
export const FEELING_IDS = ['calm','relieved','hopeful','grateful','interested','connected','safe','proud','tender','tired','sad','worried','overwhelmed','lonely','frustrated','confused','hurt','tense','joyful','content','encouraged','surprised','vulnerable','disappointed','discouraged','ashamed','guilty','irritated','angry','resentful','afraid','insecure','numb','restless','embarrassed','exhausted'] as const;
export const NEED_IDS = ['rest','safety','understanding','support','connection','belonging','autonomy','choice','clarity','honesty','respect','fairness','trust','space','boundaries','care','comfort','appreciation','competence','meaning','play','ease','stability','hope'] as const;
export const STRATEGY_IDS = ['small-step','ask-question','request-support','pause','rest'] as const;
export interface SlowlyCompanionV1 {id:string;kind:CompanionKind;sourceIds:string[];labelId:string;presentationId:'prism'|'ring'|'paired-dots'}
export interface SlowlyJourneyStateV1 {version:1;runId:string;phase:SlowlyPhase;recordOrigin:SlowlyPhase|null;endingMode:'normal'|'early';summaryDraft:string;selectedFeelings:string[];selectedNeeds:string[];companion:SlowlyCompanionV1|null;companionDraftKind:CompanionKind|null;expressionKind:'mirror'|'bridge'|'none';action:'small-step'|'request-support'|'let-go'|'rest'|'enough'|null;keepPrivateText:boolean;startedAt:number;updatedAt:number}
export interface ReflectionRecordV1 {schema:'beatgarden-reflection.v1';recordId:string;endedAt:string;outcome:SlowlyOutcome;phaseReached:SlowlyPhase;feelingIds:string[];needIds:string[];summary:string|null;companion:{kind:CompanionKind;labelId:string}|null;gameVersion:string}
export function isSlowlyJourneyStateV1(value:unknown):value is SlowlyJourneyStateV1 {if(!record(value)||value.version!==1||!exactKeys(value,['version','runId','phase','recordOrigin','endingMode','summaryDraft','selectedFeelings','selectedNeeds','companion','companionDraftKind','expressionKind','action','keepPrivateText','startedAt','updatedAt']))return false;if(!safeId(value.runId)||!SLOWLY_PHASES.includes(value.phase as SlowlyPhase)||value.phase==='ended'||!['normal','early'].includes(String(value.endingMode)))return false;const origins=['situation','feelings','needs','distill','expression','action','optionalRest'];if(value.phase==='record'?!origins.includes(String(value.recordOrigin)):value.recordOrigin!==null||value.endingMode!=='normal')return false;if(typeof value.summaryDraft!=='string'||cleanText(value.summaryDraft)!==value.summaryDraft||[...value.summaryDraft].length>240)return false;if(!enumArray(value.selectedFeelings,FEELING_IDS,3)||!enumArray(value.selectedNeeds,NEED_IDS,3))return false;if(value.companionDraftKind!==null&&!['need','strategy','insight'].includes(String(value.companionDraftKind)))return false;if(!['mirror','bridge','none'].includes(String(value.expressionKind))||![null,'small-step','request-support','let-go','rest','enough'].includes(value.action as null|string))return false;if(typeof value.keepPrivateText!=='boolean'||!finiteTime(value.startedAt)||!finiteTime(value.updatedAt)||value.updatedAt<value.startedAt)return false;return value.companion===null||isCompanion(value.companion);}
export function isReflectionRecordV1(value:unknown):value is ReflectionRecordV1 {if(!record(value)||!exactKeys(value,['schema','recordId','endedAt','outcome','phaseReached','feelingIds','needIds','summary','companion','gameVersion']))return false;if(value.schema!=='beatgarden-reflection.v1'||!safeId(value.recordId)||!Number.isFinite(Date.parse(String(value.endedAt)))||!['completed','ended-early'].includes(String(value.outcome))||!SLOWLY_PHASES.includes(value.phaseReached as SlowlyPhase))return false;if(!enumArray(value.feelingIds,FEELING_IDS,3)||!enumArray(value.needIds,NEED_IDS,3))return false;if(value.summary!==null&&(typeof value.summary!=='string'||cleanText(value.summary)!==value.summary||[...value.summary].length>240))return false;if(value.companion!==null&&(!record(value.companion)||!exactKeys(value.companion,['kind','labelId'])||!validLabel(value.companion.kind,value.companion.labelId)))return false;return typeof value.gameVersion==='string'&&value.gameVersion.length<=24;}
function isCompanion(value:unknown):value is SlowlyCompanionV1{return record(value)&&exactKeys(value,['id','kind','sourceIds','labelId','presentationId'])&&safeId(value.id)&&['need','strategy','insight'].includes(String(value.kind))&&companionIds(value.kind,value.sourceIds,value.labelId)&&['prism','ring','paired-dots'].includes(String(value.presentationId));}
function validLabel(kind:unknown,label:unknown):boolean{return kind==='need'?NEED_IDS.includes(label as typeof NEED_IDS[number]):kind==='strategy'?STRATEGY_IDS.includes(label as typeof STRATEGY_IDS[number]):kind==='insight'&&label==='authored-insight';}
function companionIds(kind:unknown,source:unknown,label:unknown):boolean{if(!safeId(label)||!Array.isArray(source)||source.length>3||new Set(source).size!==source.length)return false;if(kind==='need')return NEED_IDS.includes(label as typeof NEED_IDS[number])&&source.every(id=>NEED_IDS.includes(id as typeof NEED_IDS[number]));if(kind==='strategy')return STRATEGY_IDS.includes(label as typeof STRATEGY_IDS[number])&&source.length===1&&source[0]===label;return label==='authored-insight'&&source.every(id=>FEELING_IDS.includes(id as typeof FEELING_IDS[number]));}
function enumArray(value:unknown,allowed:readonly string[],max:number):value is string[]{return Array.isArray(value)&&value.length<=max&&new Set(value).size===value.length&&value.every(id=>typeof id==='string'&&allowed.includes(id));}
function cleanText(value:string):string{return [...value.replace(/[\u0000-\u001f\u007f]/g,'')].slice(0,4000).join('');}
function safeId(value:unknown):value is string{return typeof value==='string'&&/^[a-z0-9][a-z0-9._:-]{0,79}$/i.test(value);}
function finiteTime(value:unknown):value is number{return typeof value==='number'&&Number.isFinite(value)&&value>=0&&value<=1e16;}
function exactKeys(value:Record<string,unknown>,keys:string[]):boolean{return Object.keys(value).sort().join('|')===[...keys].sort().join('|');}
function record(value:unknown):value is Record<string,any>{return !!value&&typeof value==='object'&&!Array.isArray(value);}
